### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by MaxIsComing** [bmqb/zmxy#4]
zmxy-master/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import querystring from 'querystring';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wangwenbin/Desktop/zmxy-master/examples/app.js:2:37)
    at Module._compile (module.js:570:32)

**Comment by MaxIsComing** [comment]
这个问题怎么解决啊？

**Comment by AlloVince** [comment]
使用npm安装

**Comment by MaxIsComing** [comment]
都已经安装好了

**Comment by AlloVince** [comment]
```
$npm install zmxy --save
$ls node_modules/zmxy
LICENSE      README.md    index.js     lib          package.json
```

npm安装好之后不应该会有`/src/index.js`这个文件存在，检查一下安装方式
