### ISSUE TITLE
TypeError: Cannot read property 'RSA_PKCS1_PADDING' of undefined

### ISSUE THREAD

**Issue by johnlo1992** [bmqb/zmxy#5]
`at ZmxyClient.encrypt (.../node_modules/zmxy/lib/index.js:316:27)
    at .../node_modules/zmxy/lib/index.js:422:26
    at next (native)
    at step (.../node_modules/zmxy/lib/index.js:23:191)
    at .../node_modules/zmxy/lib/index.js:23:437
    at new Promise (.../node_modules/core-js/modules/es6.promise.js:191:7)
    at .../node_modules/zmxy/lib/index.js:23:99
    at ZmxyClient.request (.../node_modules/zmxy/lib/index.js:439:7)
    at .../node_modules/zmxy/lib/index.js:109:20
    at next (native)
`

**Comment by AlloVince** [comment]
有实际调用的代码吗，确认一下公钥和私钥有没有正确加载
